// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBujaTM5BqAyXLu5fRc85cIR3fmH-rh-_0',
    appId: '1:179827690634:web:79af3a6d18e5bd096ef173',
    messagingSenderId: '179827690634',
    projectId: 'torresjr-17e37',
    authDomain: 'torresjr-17e37.firebaseapp.com',
    storageBucket: 'torresjr-17e37.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIuhUmqlIHFzVBToKqA1J_ZtThd5p-cUM',
    appId: '1:179827690634:android:617df57080d969c66ef173',
    messagingSenderId: '179827690634',
    projectId: 'torresjr-17e37',
    storageBucket: 'torresjr-17e37.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBujaTM5BqAyXLu5fRc85cIR3fmH-rh-_0',
    appId: '1:179827690634:web:78e86f42e85126d56ef173',
    messagingSenderId: '179827690634',
    projectId: 'torresjr-17e37',
    authDomain: 'torresjr-17e37.firebaseapp.com',
    storageBucket: 'torresjr-17e37.firebasestorage.app',
  );
}
